name: Build Tailwind
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src

      - name: Create and switch to the pages branch
        run: |
          git checkout -b pages
          
      - name: Build Tailwind
        uses: actions/setup-node@v3
      - run: npx tailwindcss -i ./src/styles-input.css -o ./dist/styles.css
      - run: mv ./src/index.html ./dist/
      - run: mv ./src/main.js ./dist/
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f dist/*
          git commit -m "automatic commit"
          git push origin pages
