name: build-static
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src
        uses: actions/checkout@v4
          
      - name: Build Tailwind
        uses: actions/setup-node@v3
      - run: |
          rm .gitignore
          npx tailwindcss -i ./src/styles-input.css -o ./src/styles.css
          mv ./src/* .
          git stash

      - name: Create and switch to the pages branch
        run: |
          git switch --orphan pages
          git stash apply
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add *
          git commit -m "automatic commit"
          git push origin pages
