name: build-static
on:
  workflow_dispatch:
  push:
    branches: [master]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src
        uses: actions/checkout@v4
          
      - name: Build Tailwind
        uses: actions/setup-node@v3
      - run: |
          npx tailwindcss -i ./src/styles-input.css -o ./src/styles.css
          cp ./src/* .

      - name: Create and switch to the pages branch
        run: |
          git stash --include-untracked
          git fetch
          git switch pages
          git status
          git stash pop
          git status
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "automatic commit"
          git push origin pages
